### ISSUE TITLE
Sélection par defaut

### ISSUE THREAD

**Issue by Valolfr** [TienHai/HenkaICMN#5]
Sélectionner automatiquement la date de la prochaine rencontre. (selection par rapport à la date courante)

**Comment by TienHai** [comment]
Version 1.3 : Sélection de la prochaine date de rencontre dans le mois en cours. il me reste a sélectionner la prochaine rencontre même si elle n'est pas dans le mois en cours.

**Comment by TienHai** [comment]
Version 1.9: Sélection  de la prochaine rencontre, de manière général désormais il y a toujours une sélection de date de rencontre.
